#ifndef HEAD_H
#define HEAD_H

#include "consumer/consumer_interface.h"
#include "login.h"
#include "consumer/storepage.h"
#include "mainwindow.h"
#include "consumer/shoppingcart.h"
#include "consumer/storepage.h"
#include "logic.h"
#include "consumer/detailedmenu.h"
#include "consumer/orderstatus.h"
#include "consumer/con_reviews.h"
#include "rider/rider_inform.h"
#include"rider/rider_main.h"
#include<QMessageBox>
#include "rider/ui_rider_inform.h"
#include "rider/task_inform.h"
#include "rider/ui_task_inform.h"
#include "rider/ui_rider_main.h"
#include "rider/task_completed.h"
#include "rider/ui_task_completed.h"
#include "rider/order_review.h"
#include "rider/ui_order_review.h"
#include "business/shangjia.h"
#include "business/shangjia2.h"
#include "business/shangjia3.h"
#include "admin/admini_main.h"
#include "admin/admini_check.h"
#include "admin/admini_info.h"
#include "admin/admini_info_done.h"
#include "consumer/consumer_information.h"
#include"business/good_mange.h"
#include"business/workbench.h"
#include"business/evalute.h"
#include"business/good_act.h"
#include"business/inform.h"
#include"business/inform_change.h"
#include "business/dishchange.h"
#include "consumer/address.h"
#include "consumer/histroy_record.h"
#include "consumer/change_inform.h"
#include "consumer/complaints.h"
#endif // HEAD_H
